/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ArrayAccess: typeof import('@ts/helper/array-access.helper.ts')['ArrayAccess']
  const DeviceDetection: typeof import('@ts/helper/device-detection.helper.ts')['DeviceDetection']
  const Dom: typeof import('@ts/helper/dom.helper.ts')['Dom']
  const Formatting: typeof import('@ts/helper/formatting.helper.ts')['Formatting']
  const Selector: typeof import('@ts/helper/selector.helper.ts')['Selector']
  const Utilities: typeof import('@ts/helper/utilities.helper.ts')['Utilities']
  const bootstrap: typeof import('@ts/vendor/bootstrap/bootstrap.ts')['bootstrap']
}
